### ISSUE TITLE
[Bug] hideOptions totally prevents page from being edited

### ISSUE THREAD

**Issue by REHvision** [mullema/k3-panel-view-extended#10]
I just realized that `hideOptions` makes editing a page totally impossible. Everything I enter gets removed instantly as if the plugin intercepts every keystroke?!

![panel-view-extended-hideOptions-bug](https://user-images.githubusercontent.com/2584674/72667361-5dc5e600-3a1b-11ea-81de-22774e765c43.gif)

Looking forward to a fix, since I like the option to hide the whole options bar in some blueprints.

In the meantime, I'll stick with `hideStatus` + `hideSettings` and hide the anyways disabled navigation arrows in my panel.css via the template-specific class your plugin adds. :wink:

**Comment by mullema** [comment]
Hello REHvision
Thank you for the report. This issue has also been reported once in the forums: https://forum.getkirby.com/t/error-with-plugin-panel-view-extended-and-kirby-3-2/14816/8
The plugin does not interfere with the kirby store or field input. Therefore I don't see how it could cause this issue.

Please make sure your kirby version is up to date, clear the browser cache and kirbys media folder.

**Comment by mullema** [comment]
@REHvision I tried to look into this issue again but was not able to reproduce it. Are you still running an installation that causes this problem?

**Comment by REHvision** [comment]
Thanks @mullema,
I'm currently not working on a page where I use this function, but I'll check it again soon!

**Comment by moevbiz** [comment]
Can confirm this issue. Downloaded recent starterkit, installed plugin, added `hideOptions: true` to a `note.yml` blueprint, suddenly unable to make any changes.

When having any of this extension's custom options enabled, the browser console is giving one or more of the following errors:
```
WebSocket connection to 'wss://XXX.test:59764/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
parcelRequire.../../../../node_modules/parcel-bundler/src/builtins/hmr-runtime.js
```
or
```
app.js:1 POST https://starterkit.test/api/pages/notes+exploring-the-universe/lock 500
request @ app.js:1
post @ app.js:1
patch @ app.js:1
setLock @ app.js:1
add @ app.js:1
(anonymous) @ vendor.js:12
g.dispatch @ vendor.js:12
dispatch @ vendor.js:12
hasChanges @ app.js:1
or.run @ vendor.js:23
Zn @ vendor.js:23
(anonymous) @ vendor.js:23
fe @ vendor.js:23
Promise.then (async)
se @ vendor.js:23
me @ vendor.js:23
nr @ vendor.js:23
or.update @ vendor.js:23
gt.notify @ vendor.js:23
Rt @ vendor.js:23
UPDATE @ app.js:1
(anonymous) @ vendor.js:12
(anonymous) @ vendor.js:12
(anonymous) @ vendor.js:12
g._withCommit @ vendor.js:12
g.commit @ vendor.js:12
commit @ vendor.js:12
O.o.commit @ vendor.js:12
update @ app.js:1
(anonymous) @ vendor.js:12
g.dispatch @ vendor.js:12
dispatch @ vendor.js:12
input @ app.js:1
(anonymous) @ app.js:1
setTimeout (async)
(anonymous) @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
oe @ vendor.js:23
n @ vendor.js:23
oe @ vendor.js:23
t.$emit @ vendor.js:23
input @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
oe @ vendor.js:23
t.$emit @ vendor.js:23
save @ app.js:1
update @ app.js:1
update @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
oe @ vendor.js:23
t.$emit @ vendor.js:23
update @ app.js:1
input @ app.js:1
oe @ vendor.js:23
n @ vendor.js:23
oe @ vendor.js:23
t.$emit @ vendor.js:23
update @ app.js:1
(anonymous) @ app.js:1
emit @ app.js:1
dispatchTransaction @ app.js:1
Ln.dispatch @ vendor.js:12
le @ vendor.js:12
(anonymous) @ vendor.js:12
De.flush @ vendor.js:12
(anonymous) @ vendor.js:12
Show 34 more frames
app.js:1 {status: "error", exception: "Error", code: 0, message: "Call to a member function code() on null", details: null, …}
```
additionally and specifically for the `hideOptions` option, any key pressed is immediately deleted.

Server: Laravel Valet on Mac OS.
Kirby: v3.5.1 (starterkit)
