### ISSUE TITLE
Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by teichsta** [mullema/k3-panel-view-extended#11]
i installed you plugin as it seems to help a lot on my way to customise the kirby panel. Immediately after installation (and refreshing my panel site) i got the alert:

![image](https://user-images.githubusercontent.com/2108636/127317403-58d8529c-6ba3-457d-aff6-38bb5f820039.png)

Any idea what could cause this alert?

**Comment by mullema** [comment]
What kirby version are you using?

**Comment by teichsta** [comment]
3.5.7.1

interesting observation: at first i installed the plugin using `composer` and got the above error. I now removed the plugin again and manually copied the recent Repo-Zip from Github: the alert is gone, but the plugin doesn't seem to add all expected classes.

As `k-panel de thomas editor` is added correctly there is no additional class for k-page-view (i would expect the 'breadcrum'). Also the options doesn't seem to work. After adding 

```
options:
  hideOptions: true
```
to a page i still see the settings "Zahnrad".

Any idea where to dig deeper?

**Comment by teichsta** [comment]
ah no … observation error … the alert is still there … unfortunately

**Comment by mullema** [comment]
Try the latest release which fixes this issue

**Comment by teichsta** [comment]
thx, i did and the fix makes the alert disappear!
