### ISSUE TITLE
missing additional classes

### ISSUE THREAD

**Issue by teichsta** [mullema/k3-panel-view-extended#12]
some additional classes like the "breadcrumb" (see https://github.com/mullema/k3-panel-view-extended#additional-classes-to-k-page-view) are not added. Any idea?

**Comment by mullema** [comment]
Can you please provide more information please. Kirby version (I assume 3.5.7.1 as in the other issue), plugin version.
Any console outputs? 
I cannot reproduce this issue.

**Comment by mullema** [comment]
Weird.
What browser are you using?
Any other plugins installed?

**Comment by teichsta** [comment]
Chrome (current) + Firefox (current)

console shows (in both browser) without your plugin:

![image](https://user-images.githubusercontent.com/2108636/127346229-3de250a9-9448-4fb4-878d-8f98adf9bc85.png)

and 

![image](https://user-images.githubusercontent.com/2108636/127346476-37e58bcd-65b6-4a43-9900-fdf38abde3d7.png)

with the plugin:

![image](https://user-images.githubusercontent.com/2108636/127350628-f48948b7-2836-4dba-a25f-a3c8a349dce8.png)

**Comment by teichsta** [comment]
ok, there seems to be some interference with other plugins.

I downloaded the StarterKit, added your plugin and everything worked as expected …

Sorry for bothering and thanks for your support!!

**Comment by mullema** [comment]
No worries. Make sure my plugin is last in plugin order (just rename the folder to something like z...), that might helps
