### ISSUE TITLE
This fantastic plugin seems to not work with the version 3.5.7.1 of Kirby 

### ISSUE THREAD

**Issue by ktryndchrs** [mullema/k3-panel-view-extended#15]

**Comment by ktryndchrs** [comment]
Sorry for the late answer @mullema .

The current version of Kirby we are using is `3.5.7.1`

Ands I figured the reason which was a in-house custom plugin specific to our client needs that extends the `k-page-view`

```
export default {
  extends: 'k-page-view',
  updated ():void {
    if (this.blueprint !== 'pages/default' && this.blueprint !== 'pages/home') {
      this.$nextTick(() => {
        this.permissions.preview = false
      })
    }
  }
}

```

**Comment by mullema** [comment]
Hi @ktryndchrs 
Unfortunately these two plugins are not compatible with each other.

**Comment by ktryndchrs** [comment]
Exactly, I will figure something with my team as your plugin is quite a necessity for a better UX ojn the panel

**Comment by mullema** [comment]
In case you update to Kirby 3.6 it would be easy to just add your `updated()` method to my plugins index.js
here: https://github.com/mullema/k3-panel-view-extended/blob/78e68dd9231ebb85edf6cbf7acc6b154a599e482/index.js#L7

**Comment by ktryndchrs** [comment]
Kirby 3.6 seems like a real deal. I can't wait to play with it …

**Comment by mullema** [comment]
You can already play with it. https://github.com/getkirby/kirby/releases/tag/3.6.0-rc.3
