### ISSUE TITLE
Incompatible with the new kirby release

### ISSUE THREAD

**Issue by chrfickinger** [mullema/k3-panel-view-extended#18]
Just a short note. The Plugin stopped working with the new announced kirby release 3.7

All list views are broken:
```Cms\ModelWithContent::panelImage() has been deprecated and will be removed in Kirby 3.8.0. Use $model->panel()->image() instead.```

**Comment by distantnative** [comment]
@mullema You will have to make a few updates to mirror the changes to the `pages` section made in 3.7.0: https://github.com/getkirby/kirby/blob/develop/config/sections/pages.php#L129-L160

The deprecation warning is just one thing, but e.g. without updates your plugin would also not support the new `layout: table` feature.
