### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by mullema** [mullema/k3-panel-view-extended#3]
https://forum.getkirby.com/t/error-with-plugin-panel-view-extended-and-kirby-3-2/14816

**Comment by luxlogica** [comment]
A possible fix has been reported here:

https://forum.getkirby.com/t/error-with-plugin-panel-view-extended-and-kirby-3-2/14816/5

It is literally a one-word change, so I hope this does it! if anyone uses it, and it works, please submit a merge request with the fix - it would be greatly appreciated.

**Comment by luxlogica** [comment]
Pull Request #5 seems to fix this issue.

**Comment by mullema** [comment]
Fixed in https://github.com/mullema/k3-panel-view-extended/releases/tag/v2.0.0
