### ISSUE TITLE
Got "Cannot set property 'page' of undefined" alert on every refresh since Kirby 3.2

### ISSUE THREAD

**Issue by jesuismaxime** [mullema/k3-panel-view-extended#4]
I think it may be related to the issue #3 but since its not resolved yet lets create a new issue!

**Comment by luxlogica** [comment]
Pull Request #5 seems to fix this issue.

**Comment by mullema** [comment]
Fixed in https://github.com/mullema/k3-panel-view-extended/releases/tag/v2.0.0
