### ISSUE TITLE
Pop-up error message when manually reloading the page 

### ISSUE THREAD

**Issue by vauvarin** [mullema/k3-panel-view-extended#6]
Hi,

When I install "k3-panel-view-extended" and manually reload a panel page in my browser, I've got this pop-up message: (the message is different in Firefox and Chrome)

In Firefox
"String contains an invalid character"

In Chrome
"Failed to execute 'add' on 'DOMTokenList': The token provided ('Loredana XXX') contains HTML space characters, which are not valid in tokens."
Same message whatever the user connected.

Some blueprints in my project have some "&nbsp" in info option, don't know if it is related?

I did the test with all my plugins removed and Kirby Version 3.2.4

I also did the test with k-plainkit and the error message did not appear so it's specific to my project.

**Comment by luxlogica** [comment]
I can confirm the issue. It happens whenever the logged in User has a **username** with more than one word - example:

   * user "Tester" can refresh the panel without any problems
   * user "Tester One" gets a warning every time
   * user "TesterOne" is fine, and can refresh.

Here is the screenshot from Safari, with the JS stack trace:

<img width="1375" alt="Screen Shot 2019-09-15 at 3 59 11 pm" src="https://user-images.githubusercontent.com/2994472/64917278-d436ab00-d7d1-11e9-8b14-3cfe1f879481.png">

I believe this issue should perhaps be re-titled: "Username > 1 word gives JS error on browser refresh".

**Comment by mullema** [comment]
Thank you for your bug reports!
